trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  webAppName: 'bkamenov-app'
  resourceGroupName: 'rg01'
  location: 'westeurope'

steps:
- checkout: self

- task: AzureCLI@2
  inputs:
    azureSubscription: 'service-connection'   # <-- Your ADO service connection name here
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Creating resource group..."
      az group create --name $(resourceGroupName) --location $(location)

      echo "Deploying Bicep template..."
      az deployment group create \
        --resource-group $(resourceGroupName) \
        --template-file $(Build.SourcesDirectory)/iac/appservice.bicep \
        --parameters webAppName=$(webAppName) location=$(location)

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'webapp'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/webapp.zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'my-azure-connection'
    appType: 'webAppLinux'     # Since your app is Linux-based
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/webapp.zip'
